version: '3.2'
services:
  mongo:
    image: mongo:4.1
    expose:
      - '27017'
  api:
    build: ./backend
    environment:
      - APP_PORT=7293
      - 'APP_PUBLIC_PATH=http://localhost:7293/'
      - JWT_SECRET=my-secret-shhhhh
      - LOG_LEVEL=debug
      - MONGO_CONTACT_POINT=mongo
    expose:
      - '7293'
    depends_on:
      - mongo
    ports:
      - '7293:7293'
    volumes:
      - ./backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
  app:
    image: node:8-alpine
    ports:
      - 7292:4200
      - 49153:49153
    expose:
      - '4200'
      - '49153'
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    working_dir: "/usr/src/app"
    environment:
      - API_URL=api:7293
    depends_on:
      - api
    command: /bin/sh -c "echo 'Install packages...'; npm install; npm run start"
volumes:
  backend_node_modules:
  frontend_node_modules:

