version: '3.2'
services:
  cleachtadh:
    build: .
    environment:
      - APP_PORT=7293
      - MONGO_CONTACT_POINT=mongo
    expose:
      - '7293'
    depends_on:
      - mongo
  mongo:
    image: mongo:4.1
    expose:
      - '27017'
volumes:
  node_modules:

