#!/bin/sh

# Launch the application and any extra required processes locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update

# If no NODE_ENV is set, default to development
test -z "$NODE_ENV" &&
  NODE_ENV="development"

# If NODE_INSPECT is truthly launch node with --inspect
if [ -n "$NODE_INSPECT" ]
then
  echo "==> Starting the server in debug mode..."
  npm run debug
else
  echo "==> Starting the server..."
  npm start
fi
