#!/bin/sh

# Run test suite for application. Optionally pass in a path to an
# individual test file to run a single test.

set -e

cd "$(dirname "$0")/.."

export NODE_ENV="test" # Ensure we are in test environment

./script/update

echo "===> Running tests..."

if [ -n "$1" ]; then
  # pass arguments to test call. This is useful for calling a single test.
  npm test -- ${@}
else
  npm test
fi
